/*
 * Criteo API Transition Swagger
 * This is used to help Criteo clients transition from MAPI to Criteo API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.marketing.model.NillableAdSetTargetingRule;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ad set geolocation model
 */
@ApiModel(description = "ad set geolocation model")

public class AdSetGeoLocation {
  public static final String SERIALIZED_NAME_COUNTRIES = "countries";
  @SerializedName(SERIALIZED_NAME_COUNTRIES)
  private NillableAdSetTargetingRule countries;

  public static final String SERIALIZED_NAME_SUBDIVISIONS = "subdivisions";
  @SerializedName(SERIALIZED_NAME_SUBDIVISIONS)
  private NillableAdSetTargetingRule subdivisions;

  public static final String SERIALIZED_NAME_ZIP_CODES = "zipCodes";
  @SerializedName(SERIALIZED_NAME_ZIP_CODES)
  private NillableAdSetTargetingRule zipCodes;


  public AdSetGeoLocation countries(NillableAdSetTargetingRule countries) {
    
    this.countries = countries;
    return this;
  }

   /**
   * Get countries
   * @return countries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NillableAdSetTargetingRule getCountries() {
    return countries;
  }



  public void setCountries(NillableAdSetTargetingRule countries) {
    this.countries = countries;
  }


  public AdSetGeoLocation subdivisions(NillableAdSetTargetingRule subdivisions) {
    
    this.subdivisions = subdivisions;
    return this;
  }

   /**
   * Get subdivisions
   * @return subdivisions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NillableAdSetTargetingRule getSubdivisions() {
    return subdivisions;
  }



  public void setSubdivisions(NillableAdSetTargetingRule subdivisions) {
    this.subdivisions = subdivisions;
  }


  public AdSetGeoLocation zipCodes(NillableAdSetTargetingRule zipCodes) {
    
    this.zipCodes = zipCodes;
    return this;
  }

   /**
   * Get zipCodes
   * @return zipCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NillableAdSetTargetingRule getZipCodes() {
    return zipCodes;
  }



  public void setZipCodes(NillableAdSetTargetingRule zipCodes) {
    this.zipCodes = zipCodes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdSetGeoLocation adSetGeoLocation = (AdSetGeoLocation) o;
    return Objects.equals(this.countries, adSetGeoLocation.countries) &&
        Objects.equals(this.subdivisions, adSetGeoLocation.subdivisions) &&
        Objects.equals(this.zipCodes, adSetGeoLocation.zipCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countries, subdivisions, zipCodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdSetGeoLocation {\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    subdivisions: ").append(toIndentedString(subdivisions)).append("\n");
    sb.append("    zipCodes: ").append(toIndentedString(zipCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

