/*
 * Criteo API Transition Swagger
 * This is used to help Criteo clients transition from MAPI to Criteo API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject
 */

public class InlineObject {
  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  private String clientId;

  public static final String SERIALIZED_NAME_CLIENT_SECRET = "client_secret";
  @SerializedName(SERIALIZED_NAME_CLIENT_SECRET)
  private String clientSecret;

  public static final String SERIALIZED_NAME_GRANT_TYPE = "grant_type";
  @SerializedName(SERIALIZED_NAME_GRANT_TYPE)
  private String grantType = "client_credentials";


  public InlineObject clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * API Client-Id or Username
   * @return clientId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "API Client-Id or Username")

  public String getClientId() {
    return clientId;
  }



  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public InlineObject clientSecret(String clientSecret) {
    
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * API Client secret or password
   * @return clientSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "API Client secret or password")

  public String getClientSecret() {
    return clientSecret;
  }



  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }


  public InlineObject grantType(String grantType) {
    
    this.grantType = grantType;
    return this;
  }

   /**
   * Other grant types are not available
   * @return grantType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other grant types are not available")

  public String getGrantType() {
    return grantType;
  }



  public void setGrantType(String grantType) {
    this.grantType = grantType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return Objects.equals(this.clientId, inlineObject.clientId) &&
        Objects.equals(this.clientSecret, inlineObject.clientSecret) &&
        Objects.equals(this.grantType, inlineObject.grantType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, grantType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

