/*
 * Criteo API Transition Swagger
 * This is used to help Criteo clients transition from MAPI to Criteo API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NewAudienceAttributes
 */

public class NewAudienceAttributes {
  public static final String SERIALIZED_NAME_ADVERTISER_ID = "advertiserId";
  @SerializedName(SERIALIZED_NAME_ADVERTISER_ID)
  private String advertiserId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;


  public NewAudienceAttributes advertiserId(String advertiserId) {
    
    this.advertiserId = advertiserId;
    return this;
  }

   /**
   * The advertiser id to create the audience for
   * @return advertiserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The advertiser id to create the audience for")

  public String getAdvertiserId() {
    return advertiserId;
  }



  public void setAdvertiserId(String advertiserId) {
    this.advertiserId = advertiserId;
  }


  public NewAudienceAttributes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the new audience
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the new audience")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public NewAudienceAttributes description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the audience
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the audience")

  public String getDescription() {
    return description;
  }



  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewAudienceAttributes newAudienceAttributes = (NewAudienceAttributes) o;
    return Objects.equals(this.advertiserId, newAudienceAttributes.advertiserId) &&
        Objects.equals(this.name, newAudienceAttributes.name) &&
        Objects.equals(this.description, newAudienceAttributes.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(advertiserId, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewAudienceAttributes {\n");
    sb.append("    advertiserId: ").append(toIndentedString(advertiserId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

